In [4]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import scipy.stats as stats
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder as One
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestClassifier
from sklearn.tree import DecisionTreeClassifier
from sklearn.metrics import accuracy_score,classification_report,confusion_matrix
import pickle
from sklearn.preprocessing import LabelEncoder, StandardScaler

In [5]:
data=pd.read_csv("normalized.csv")
genre_list = data.iloc[:, -1]
genre_list

0       0
1       0
2       0
3       0
4       0
       ..
4211    2
4212    2
4213    2
4214    2
4215    2
Name: Unnamed: 5, Length: 4216, dtype: int64

In [6]:

encoder = LabelEncoder()
y = encoder.fit_transform(genre_list)
y

array([0, 0, 0, ..., 2, 2, 2])

In [7]:
y = np.array(y)
y= y.reshape(4216,1)
y

array([[0],
       [0],
       [0],
       ...,
       [2],
       [2],
       [2]])

In [8]:
scaler = StandardScaler()

X = np.array(data.iloc[:, :-3], dtype = float)
print(X)
print(len(X))

[[47.33 89.9  16.46]
 [53.8  69.82 10.02]
 [55.02 65.32 12.31]
 ...
 [19.53 91.4  71.64]
 [19.54 91.   71.36]
 [19.91 91.5  71.97]]
4216


In [13]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(X,y,test_size=0.2,random_state=0)

In [14]:

rfc = RandomForestClassifier(n_estimators=100,random_state = 0)
rfc.fit(x_train, y_train)

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:3: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  This is separate from the ipykernel package so we can avoid doing imports until


RandomForestClassifier(bootstrap=True, ccp_alpha=0.0, class_weight=None,
                       criterion='gini', max_depth=None, max_features='auto',
                       max_leaf_nodes=None, max_samples=None,
                       min_impurity_decrease=0.0, min_impurity_split=None,
                       min_samples_leaf=1, min_samples_split=2,
                       min_weight_fraction_leaf=0.0, n_estimators=100,
                       n_jobs=None, oob_score=False, random_state=0, verbose=0,
                       warm_start=False)

In [15]:
rfc_pred = rfc.predict(x_test)

print(confusion_matrix(y_test,rfc_pred))

print(classification_report(y_test,rfc_pred))

[[199   1  36]
 [  4  15   4]
 [ 12   1 572]]
              precision    recall  f1-score   support

           0       0.93      0.84      0.88       236
           1       0.88      0.65      0.75        23
           2       0.93      0.98      0.96       585

    accuracy                           0.93       844
   macro avg       0.91      0.82      0.86       844
weighted avg       0.93      0.93      0.93       844



In [16]:

rfc.score(x_test,y_test)


0.9312796208530806