In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.metrics import accuracy_score, confusion_matrix
import pickle

In [2]:
dataset=pd.read_csv("Avalanche.csv")
dataset

Slope Forest Density  Snow Density  Air Temperature  Wind  Prediction
0       59              H            52              -17    19           2
1       24              L            23               -8    19           0
2       15              H            30                7    19           0
3       27              L            61              -13    25           1
4       34              H             4              -20     7           0
..     ...            ...           ...              ...   ...         ...
199     34              M            44                6     6           0
200     34              L            73              -34    13           2
201     34              M            33               13    35           1
202     34              L            51               -4    35           1
203     34              M            59              -29     8           2

[204 rows x 6 columns]

In [3]:
dataset.describe()

Slope  Snow Density  Air Temperature        Wind  Prediction
count  204.000000    204.000000       204.000000  204.000000  204.000000
mean    44.024510     39.553922        -9.289216   22.411765    1.049020
std     19.045044     24.485082        15.023452   11.815789    0.773673
min     12.000000      1.000000       -34.000000    6.000000    0.000000
25%     33.000000     16.000000       -22.000000   11.000000    0.000000
50%     36.000000     42.000000       -10.500000   22.000000    1.000000
75%     59.000000     61.000000         6.000000   35.000000    2.000000
max     80.000000     78.000000        15.000000   40.000000    2.000000

In [4]:
dataset.corr()

Slope  Snow Density  Air Temperature      Wind  Prediction
Slope            1.000000      0.066079         0.065655 -0.043279    0.487693
Snow Density     0.066079      1.000000        -0.046312  0.066345    0.454154
Air Temperature  0.065655     -0.046312         1.000000  0.077987   -0.200510
Wind            -0.043279      0.066345         0.077987  1.000000   -0.014613
Prediction       0.487693      0.454154        -0.200510 -0.014613    1.000000

In [5]:
x=dataset.iloc[:,0:5].values
x

array([[59, 'H', 52, -17, 19],
       [24, 'L', 23, -8, 19],
       [15, 'H', 30, 7, 19],
       ...,
       [34, 'M', 33, 13, 35],
       [34, 'L', 51, -4, 35],
       [34, 'M', 59, -29, 8]], dtype=object)

In [6]:
y=dataset.iloc[:,5:].values
y

array([[2],
       [0],
       [0],
       [1],
       [0],
       [1],
       [2],
       [1],
       [0],
       [2],
       [1],
       [1],
       [2],
       [2],
       [2],
       [2],
       [2],
       [1],
       [1],
       [0],
       [1],
       [1],
       [0],
       [0],
       [2],
       [1],
       [1],
       [2],
       [2],
       [1],
       [1],
       [2],
       [1],
       [2],
       [0],
       [2],
       [1],
       [2],
       [2],
       [2],
       [1],
       [2],
       [1],
       [2],
       [1],
       [0],
       [1],
       [2],
       [0],
       [1],
       [2],
       [1],
       [0],
       [1],
       [1],
       [0],
       [0],
       [0],
       [2],
       [2],
       [1],
       [0],
       [0],
       [1],
       [0],
       [1],
       [1],
       [0],
       [2],
       [1],
       [2],
       [0],
       [1],
       [1],
       [2],
       [0],
       [2],
       [0],
       [0],
       [1],
       [1],
       [2],
       [1],
    

In [7]:
data=dataset['Forest Density'].value_counts()
points=data.index
points

Index(['L', 'M', 'H'], dtype='object')

In [8]:
data=dataset['Forest Density'].value_counts()
data

L    76
M    66
H    62
Name: Forest Density, dtype: int64

In [9]:
from sklearn.preprocessing import LabelEncoder
lb=LabelEncoder()

In [10]:
x[:,1]=lb.fit_transform(x[:,1])
x

array([[59, 0, 52, -17, 19],
       [24, 1, 23, -8, 19],
       [15, 0, 30, 7, 19],
       ...,
       [34, 2, 33, 13, 35],
       [34, 1, 51, -4, 35],
       [34, 2, 59, -29, 8]], dtype=object)

In [11]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
ct=ColumnTransformer([("on",OneHotEncoder(),[1])],remainder="passthrough")
x=ct.fit_transform(x)
x

array([[1.0, 0.0, 0.0, ..., 52, -17, 19],
       [0.0, 1.0, 0.0, ..., 23, -8, 19],
       [1.0, 0.0, 0.0, ..., 30, 7, 19],
       ...,
       [0.0, 0.0, 1.0, ..., 33, 13, 35],
       [0.0, 1.0, 0.0, ..., 51, -4, 35],
       [0.0, 0.0, 1.0, ..., 59, -29, 8]], dtype=object)

In [12]:
x=x[:,1:]
x

array([[0.0, 0.0, 59, 52, -17, 19],
       [1.0, 0.0, 24, 23, -8, 19],
       [0.0, 0.0, 15, 30, 7, 19],
       ...,
       [0.0, 1.0, 34, 33, 13, 35],
       [1.0, 0.0, 34, 51, -4, 35],
       [0.0, 1.0, 34, 59, -29, 8]], dtype=object)

In [18]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.1,random_state=0)

In [19]:
from sklearn.preprocessing import StandardScaler
sc=StandardScaler()
x_train=sc.fit_transform(x_train)
x_test=sc.transform(x_test)

In [20]:
from sklearn.tree import DecisionTreeClassifier
dt=DecisionTreeClassifier(random_state=0,criterion='gini')
dt.fit(x_train,y_train)

DecisionTreeClassifier(ccp_alpha=0.0, class_weight=None, criterion='gini',
                       max_depth=None, max_features=None, max_leaf_nodes=None,
                       min_impurity_decrease=0.0, min_impurity_split=None,
                       min_samples_leaf=1, min_samples_split=2,
                       min_weight_fraction_leaf=0.0, presort='deprecated',
                       random_state=0, splitter='best')

In [21]:
y_predict=dt.predict(x_test)
y_predict

array([1, 2, 2, 2, 1, 1, 1, 1, 2, 0, 0, 1, 2, 0, 1, 1, 0, 1, 0, 1, 0])

In [22]:
accuracy=accuracy_score(y_test,y_predict)
print("Accuracy of the model:", accuracy)

Accuracy of the model: 0.9047619047619048
