In [1]:
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt

In [2]:
dataset=pd.read_csv("Avalanche.csv")
dataset

Slope Forest Density  Snow Density  Air Temperature  Wind  Prediction
0       59              H            52              -17    19           2
1       24              L            23               -8    19           0
2       15              H            30                7    19           0
3       27              L            61              -13    25           1
4       34              H             4              -20     7           0
..     ...            ...           ...              ...   ...         ...
199     34              M            44                6     6           0
200     34              L            73              -34    13           2
201     34              M            33               13    35           1
202     34              L            51               -4    35           1
203     34              M            59              -29     8           2

[204 rows x 6 columns]

In [3]:
from sklearn.preprocessing import LabelEncoder
le  = LabelEncoder()

In [4]:
dataset["Forest Density"] = le.fit_transform(dataset["Forest Density"])

In [5]:
x = dataset.iloc[:,0:5].values
y = dataset.iloc[:,5:6].values

In [6]:
y.shape
y.ravel()

array([2, 0, 0, 1, 0, 1, 2, 1, 0, 2, 1, 1, 2, 2, 2, 2, 2, 1, 1, 0, 1, 1,
       0, 0, 2, 1, 1, 2, 2, 1, 1, 2, 1, 2, 0, 2, 1, 2, 2, 2, 1, 2, 1, 2,
       1, 0, 1, 2, 0, 1, 2, 1, 0, 1, 1, 0, 0, 0, 2, 2, 1, 0, 0, 1, 0, 1,
       1, 0, 2, 1, 2, 0, 1, 1, 2, 0, 2, 0, 0, 1, 1, 2, 1, 2, 1, 1, 1, 0,
       2, 0, 1, 1, 1, 2, 2, 1, 2, 1, 2, 2, 0, 0, 1, 0, 1, 2, 1, 0, 2, 1,
       1, 2, 2, 2, 2, 2, 1, 1, 0, 1, 1, 2, 0, 0, 1, 0, 1, 2, 1, 0, 2, 1,
       1, 2, 2, 2, 2, 2, 1, 1, 0, 1, 1, 1, 0, 0, 0, 2, 2, 1, 0, 0, 1, 0,
       1, 1, 0, 2, 1, 2, 0, 1, 1, 2, 0, 2, 2, 1, 0, 0, 1, 0, 1, 1, 0, 2,
       1, 2, 0, 2, 2, 1, 0, 0, 1, 0, 1, 1, 0, 2, 1, 2, 0, 0, 1, 0, 1, 2,
       1, 0, 2, 1, 1, 2])

In [32]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test = train_test_split(x,y,test_size=0.20,random_state=0)

In [33]:
from sklearn.svm import SVC
svclassifier = SVC(kernel='rbf')
svclassifier.fit(x_train, y_train)

/usr/local/lib/python3.7/dist-packages/sklearn/utils/validation.py:760: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


SVC(C=1.0, break_ties=False, cache_size=200, class_weight=None, coef0=0.0,
    decision_function_shape='ovr', degree=3, gamma='scale', kernel='rbf',
    max_iter=-1, probability=False, random_state=None, shrinking=True,
    tol=0.001, verbose=False)

In [34]:
y_pred = svclassifier.predict(x_test)

In [35]:
from sklearn.metrics import classification_report, confusion_matrix
print(confusion_matrix(y_test,y_pred))
print(classification_report(y_test,y_pred))

[[11  2  0]
 [ 3 15  1]
 [ 0  3  6]]
              precision    recall  f1-score   support

           0       0.79      0.85      0.81        13
           1       0.75      0.79      0.77        19
           2       0.86      0.67      0.75         9

    accuracy                           0.78        41
   macro avg       0.80      0.77      0.78        41
weighted avg       0.78      0.78      0.78        41



In [36]:
from sklearn import metrics
print("Accuracy:",metrics.accuracy_score(y_test, y_pred))

Accuracy: 0.7804878048780488
