In [1]:
import numpy as np
import pandas as pd

from sklearn.preprocessing import LabelEncoder, StandardScaler

data=pd.read_csv("normalized.csv")

genre_list = data.iloc[:, -1]
genre_list

encoder = LabelEncoder()
y = encoder.fit_transform(genre_list)

y = np.array(y)
y= y.reshape(4216,1)
y

X = np.array(data.iloc[:, :-3], dtype = float)
print(X)
print(len(X))

[[47.33 89.9  16.46]
 [53.8  69.82 10.02]
 [55.02 65.32 12.31]
 ...
 [19.53 91.4  71.64]
 [19.54 91.   71.36]
 [19.91 91.5  71.97]]
4216


In [2]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(X,y,test_size=0.2,random_state=0)

In [3]:
#Import Gaussian Naive Bayes model
from sklearn.naive_bayes import GaussianNB

#Create a Gaussian Classifier
gnb = GaussianNB()

#Train the model using the training sets
gnb.fit(x_train, y_train)

#Predict the response for test dataset
y_pred = gnb.predict(x_test)

/usr/local/lib/python3.7/dist-packages/sklearn/naive_bayes.py:206: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


In [4]:
#Import scikit-learn metrics module for accuracy calculation
from sklearn import metrics

# Model Accuracy, how often is the classifier correct?
print("Accuracy:",metrics.accuracy_score(y_test, y_pred))

Accuracy: 0.8601895734597157
