In [1]:
import numpy as np
import pandas as pd

from sklearn.preprocessing import LabelEncoder, StandardScaler

dataset=pd.read_csv("Avalanche.csv")

In [2]:
from sklearn.preprocessing import LabelEncoder
le  = LabelEncoder()


In [3]:
dataset["Forest Density"] = le.fit_transform(dataset["Forest Density"])

In [4]:

x=dataset.iloc[:,0:5].values
x

array([[ 59,   0,  52, -17,  19],
       [ 24,   1,  23,  -8,  19],
       [ 15,   0,  30,   7,  19],
       ...,
       [ 34,   2,  33,  13,  35],
       [ 34,   1,  51,  -4,  35],
       [ 34,   2,  59, -29,   8]])

In [5]:
y=dataset.iloc[:,5:].values
y

array([[2],
       [0],
       [0],
       [1],
       [0],
       [1],
       [2],
       [1],
       [0],
       [2],
       [1],
       [1],
       [2],
       [2],
       [2],
       [2],
       [2],
       [1],
       [1],
       [0],
       [1],
       [1],
       [0],
       [0],
       [2],
       [1],
       [1],
       [2],
       [2],
       [1],
       [1],
       [2],
       [1],
       [2],
       [0],
       [2],
       [1],
       [2],
       [2],
       [2],
       [1],
       [2],
       [1],
       [2],
       [1],
       [0],
       [1],
       [2],
       [0],
       [1],
       [2],
       [1],
       [0],
       [1],
       [1],
       [0],
       [0],
       [0],
       [2],
       [2],
       [1],
       [0],
       [0],
       [1],
       [0],
       [1],
       [1],
       [0],
       [2],
       [1],
       [2],
       [0],
       [1],
       [1],
       [2],
       [0],
       [2],
       [0],
       [0],
       [1],
       [1],
       [2],
       [1],
    

In [6]:
encoder = LabelEncoder()
y = encoder.fit_transform(y)
y

/usr/local/lib/python3.7/dist-packages/sklearn/preprocessing/_label.py:251: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


array([2, 0, 0, 1, 0, 1, 2, 1, 0, 2, 1, 1, 2, 2, 2, 2, 2, 1, 1, 0, 1, 1,
       0, 0, 2, 1, 1, 2, 2, 1, 1, 2, 1, 2, 0, 2, 1, 2, 2, 2, 1, 2, 1, 2,
       1, 0, 1, 2, 0, 1, 2, 1, 0, 1, 1, 0, 0, 0, 2, 2, 1, 0, 0, 1, 0, 1,
       1, 0, 2, 1, 2, 0, 1, 1, 2, 0, 2, 0, 0, 1, 1, 2, 1, 2, 1, 1, 1, 0,
       2, 0, 1, 1, 1, 2, 2, 1, 2, 1, 2, 2, 0, 0, 1, 0, 1, 2, 1, 0, 2, 1,
       1, 2, 2, 2, 2, 2, 1, 1, 0, 1, 1, 2, 0, 0, 1, 0, 1, 2, 1, 0, 2, 1,
       1, 2, 2, 2, 2, 2, 1, 1, 0, 1, 1, 1, 0, 0, 0, 2, 2, 1, 0, 0, 1, 0,
       1, 1, 0, 2, 1, 2, 0, 1, 1, 2, 0, 2, 2, 1, 0, 0, 1, 0, 1, 1, 0, 2,
       1, 2, 0, 2, 2, 1, 0, 0, 1, 0, 1, 1, 0, 2, 1, 2, 0, 0, 1, 0, 1, 2,
       1, 0, 2, 1, 1, 2])

In [7]:
y = np.array(y)
y= y.reshape(204,1)
y

array([[2],
       [0],
       [0],
       [1],
       [0],
       [1],
       [2],
       [1],
       [0],
       [2],
       [1],
       [1],
       [2],
       [2],
       [2],
       [2],
       [2],
       [1],
       [1],
       [0],
       [1],
       [1],
       [0],
       [0],
       [2],
       [1],
       [1],
       [2],
       [2],
       [1],
       [1],
       [2],
       [1],
       [2],
       [0],
       [2],
       [1],
       [2],
       [2],
       [2],
       [1],
       [2],
       [1],
       [2],
       [1],
       [0],
       [1],
       [2],
       [0],
       [1],
       [2],
       [1],
       [0],
       [1],
       [1],
       [0],
       [0],
       [0],
       [2],
       [2],
       [1],
       [0],
       [0],
       [1],
       [0],
       [1],
       [1],
       [0],
       [2],
       [1],
       [2],
       [0],
       [1],
       [1],
       [2],
       [0],
       [2],
       [0],
       [0],
       [1],
       [1],
       [2],
       [1],
    

In [9]:
scaler = StandardScaler()

X = np.array(dataset.iloc[:, :-1], dtype = float)
print(X)
print(len(X))

[[ 59.   0.  52. -17.  19.]
 [ 24.   1.  23.  -8.  19.]
 [ 15.   0.  30.   7.  19.]
 ...
 [ 34.   2.  33.  13.  35.]
 [ 34.   1.  51.  -4.  35.]
 [ 34.   2.  59. -29.   8.]]
204


In [10]:
from keras import models 
from keras import layers

model = models.Sequential()

model.add(layers.Dense(64, activation='relu', input_shape=(x.shape[1],)))

model.add(layers.Dense(16, activation='relu'))

model.add(layers.Dense(32, activation='relu'))

model.add(layers.Dense(64, activation='relu'))

model.add(layers.Dense(128, activation='relu'))

model.add(layers.Dense(32, activation='relu'))

model.add(layers.Dense(16, activation='relu'))

model.add(layers.Dense(3, activation='softmax'))

model.compile(optimizer='adam', loss='sparse_categorical_crossentropy', metrics=['accuracy'])

epochs=100

model.fit(x, y, epochs=epochs)

model.save('NN.h5') 
print(' ') 
print("Training completed")

Epoch 1/100
7/7 [==============================] - 1s 3ms/step - loss: 1.1722 - accuracy: 0.3402
Epoch 2/100
7/7 [==============================] - 0s 4ms/step - loss: 0.9445 - accuracy: 0.5221
Epoch 3/100
7/7 [==============================] - 0s 3ms/step - loss: 0.8500 - accuracy: 0.6451
Epoch 4/100
7/7 [==============================] - 0s 3ms/step - loss: 0.8138 - accuracy: 0.6746
Epoch 5/100
7/7 [==============================] - 0s 3ms/step - loss: 0.7703 - accuracy: 0.6394
Epoch 6/100
7/7 [==============================] - 0s 3ms/step - loss: 0.7386 - accuracy: 0.6497
Epoch 7/100
7/7 [==============================] - 0s 4ms/step - loss: 0.6655 - accuracy: 0.7262
Epoch 8/100
7/7 [==============================] - 0s 3ms/step - loss: 0.6901 - accuracy: 0.7160
Epoch 9/100
7/7 [==============================] - 0s 3ms/step - loss: 0.6481 - accuracy: 0.7313
Epoch 10/100
7/7 [==============================] - 0s 3ms/step - loss: 0.6722 - accuracy: 0.7225
Epoch 11/100
7/7 [===========