In [8]:
import numpy as np
import pandas as pd

from sklearn.preprocessing import LabelEncoder, StandardScaler

data=pd.read_csv("normalized.csv")


In [15]:
data

Temperature (deg F)  Relative Humidity (%)  ...  Unnamed: 4  Unnamed: 5
0                   47.33                  89.90  ...    0.000000           0
1                   53.80                  69.82  ...    0.000000           0
2                   55.02                  65.32  ...    0.000000           0
3                   56.62                  54.77  ...    0.000000           0
4                   54.93                  58.87  ...    0.000000           0
...                   ...                    ...  ...         ...         ...
4211                19.78                  91.60  ...    0.943697           2
4212                19.54                  91.50  ...    0.943697           2
4213                19.53                  91.40  ...    0.940467           2
4214                19.54                  91.00  ...    0.940506           2
4215                19.91                  91.50  ...    0.940529           2

[4216 rows x 6 columns]

In [9]:
genre_list = data.iloc[:, -1]
genre_list

0       0
1       0
2       0
3       0
4       0
       ..
4211    2
4212    2
4213    2
4214    2
4215    2
Name: Unnamed: 5, Length: 4216, dtype: int64

In [10]:
encoder = LabelEncoder()
y = encoder.fit_transform(genre_list)
y


array([0, 0, 0, ..., 2, 2, 2])

In [11]:
y = np.array(y)
y= y.reshape(4216,1)
y

array([[0],
       [0],
       [0],
       ...,
       [2],
       [2],
       [2]])

In [16]:
scaler = StandardScaler()

X = np.array(data.iloc[:, :-3], dtype = float)
print(X)
print(len(X))



[[47.33 89.9  16.46]
 [53.8  69.82 10.02]
 [55.02 65.32 12.31]
 ...
 [19.53 91.4  71.64]
 [19.54 91.   71.36]
 [19.91 91.5  71.97]]
4216


In [18]:
from keras import models 
from keras import layers

model = models.Sequential()

model.add(layers.Dense(64, activation='relu', input_shape=(X.shape[1],)))

model.add(layers.Dense(16, activation='relu'))

model.add(layers.Dense(32, activation='relu'))

model.add(layers.Dense(64, activation='relu'))

model.add(layers.Dense(128, activation='relu'))

model.add(layers.Dense(32, activation='relu'))

model.add(layers.Dense(16, activation='relu'))

model.add(layers.Dense(3, activation='softmax'))

model.compile(optimizer='adam', loss='sparse_categorical_crossentropy', metrics=['accuracy'])

epochs=1000

model.fit(X, y, epochs=epochs)

model.save('NN.h5') 
print(' ') 
print("Training completed")

Epoch 1/1000
132/132 [==============================] - 1s 2ms/step - loss: 0.5122 - accuracy: 0.8240
Epoch 2/1000
132/132 [==============================] - 0s 2ms/step - loss: 0.3735 - accuracy: 0.8735
Epoch 3/1000
132/132 [==============================] - 0s 2ms/step - loss: 0.3316 - accuracy: 0.8786
Epoch 4/1000
132/132 [==============================] - 0s 2ms/step - loss: 0.3346 - accuracy: 0.8788
Epoch 5/1000
132/132 [==============================] - 0s 2ms/step - loss: 0.3417 - accuracy: 0.8781
Epoch 6/1000
132/132 [==============================] - 0s 2ms/step - loss: 0.3437 - accuracy: 0.8731
Epoch 7/1000
132/132 [==============================] - 0s 2ms/step - loss: 0.3103 - accuracy: 0.8780
Epoch 8/1000
132/132 [==============================] - 0s 2ms/step - loss: 0.3343 - accuracy: 0.8799
Epoch 9/1000
132/132 [==============================] - 0s 2ms/step - loss: 0.3042 - accuracy: 0.8831
Epoch 10/1000
132/132 [==============================] - 0s 2ms/step - loss: 0.309