In [1]:
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt
import sklearn
dataset=pd.read_csv("Avalanche.csv")
dataset
from sklearn.preprocessing import LabelEncoder
le  = LabelEncoder()
dataset["Forest Density"] = le.fit_transform(dataset["Forest Density"])
x = dataset.iloc[:,0:5].values
y = dataset.iloc[:,5:6].values

In [3]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test=train_test_split(x,y,test_size=0.2,random_state=0)

In [4]:
from sklearn.preprocessing import StandardScaler

sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)

In [5]:
from sklearn.decomposition import PCA

pca = PCA()
X_train = pca.fit_transform(X_train)
X_test = pca.transform(X_test)

In [6]:
explained_variance = pca.explained_variance_ratio_

In [12]:
from sklearn.decomposition import PCA

pca = PCA(n_components=1)
X_train = pca.fit_transform(X_train)
X_test = pca.transform(X_test)

In [10]:
from sklearn.metrics import confusion_matrix
from sklearn.metrics import accuracy_score

cm = confusion_matrix(y_test, y_pred)
print(cm)
print('Accuracy' ,accuracy_score(y_test, y_pred))

[[ 0  9  4]
 [ 0 13  6]
 [ 0  3  6]]
Accuracy 0.4634146341463415
