In [1]:
import numpy as np
import pandas as pd

from sklearn.preprocessing import LabelEncoder, StandardScaler

data=pd.read_csv("normalized.csv")

In [2]:
genre_list = data.iloc[:, -1]
genre_list

0       0
1       0
2       0
3       0
4       0
       ..
4211    2
4212    2
4213    2
4214    2
4215    2
Name: Unnamed: 5, Length: 4216, dtype: int64

In [3]:
encoder = LabelEncoder()
y = encoder.fit_transform(genre_list)
y

array([0, 0, 0, ..., 2, 2, 2])

In [4]:
y = np.array(y)
y= y.reshape(4216,1)
y

array([[0],
       [0],
       [0],
       ...,
       [2],
       [2],
       [2]])

In [5]:
X = np.array(data.iloc[:, :-3], dtype = float)
print(X)
print(len(X))

[[47.33 89.9  16.46]
 [53.8  69.82 10.02]
 [55.02 65.32 12.31]
 ...
 [19.53 91.4  71.64]
 [19.54 91.   71.36]
 [19.91 91.5  71.97]]
4216


In [39]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test = train_test_split(X,y,test_size=0.20,random_state=0)

In [40]:
from sklearn.svm import SVC
svclassifier = SVC(kernel='sigmoid')
svclassifier.fit(x_train, y_train)

/usr/local/lib/python3.7/dist-packages/sklearn/utils/validation.py:760: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


SVC(C=1.0, break_ties=False, cache_size=200, class_weight=None, coef0=0.0,
    decision_function_shape='ovr', degree=3, gamma='scale', kernel='sigmoid',
    max_iter=-1, probability=False, random_state=None, shrinking=True,
    tol=0.001, verbose=False)

In [41]:
y_pred = svclassifier.predict(x_test)

In [42]:
from sklearn.metrics import classification_report, confusion_matrix
print(confusion_matrix(y_test,y_pred))
print(classification_report(y_test,y_pred))

[[  0   0 236]
 [  0   0  23]
 [  0   0 585]]
              precision    recall  f1-score   support

           0       0.00      0.00      0.00       236
           1       0.00      0.00      0.00        23
           2       0.69      1.00      0.82       585

    accuracy                           0.69       844
   macro avg       0.23      0.33      0.27       844
weighted avg       0.48      0.69      0.57       844



/usr/local/lib/python3.7/dist-packages/sklearn/metrics/_classification.py:1272: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


In [43]:
from sklearn import metrics
print("Accuracy:",metrics.accuracy_score(y_test, y_pred))

Accuracy: 0.693127962085308
